import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:islamy_app/modules/quran/SuraName.dart';
import 'package:islamy_app/styles/themes.dart';

class QuranPage extends StatelessWidget {
  List<String> suraNamesList = [
    "ٱلْفَاتِحَة",
    "ٱلْبَقَرَة",
    "آلِ عِمْرَان",
    "ٱلنِّسَاء",
    "ٱلْمَائِدَة",
    "ٱلْأَنْعَام",
    "ٱلْأَعْرَاف",
    "ٱلْأَنْفَال",
    "ٱلتَّوْبَة",
    "يُونُس",
    "هُود",
    "يُوسُف",
    "ٱلرَّعْد",
    "إِبْرَاهِيم",
    "ٱلْحِجْر",
    "ٱلنَّحْل",
    "ٱلْإِسْرَاء",
    "ٱلْكَهْف",
    "مَرْيَم",
    "طه",
    "ٱلْأَنْبِيَاء",
    "ٱلْحَجّ",
    "ٱلْمُؤْمِنُون",
    "ٱلنُّور",
    "ٱلْفُرْقَان",
    "ٱلشُّعَرَاء",
    "ٱلنَّمْل",
    "ٱلْقَصَص",
    "ٱلْعَنْكَبُوت",
    "ٱلرُّوم",
    "لُقْمَان",
    "ٱلسَّجْدَة",
    "ٱلْأَحْزَاب",
    "سَبَأ",
    "فَاطِر",
    "يس",
    "ٱلصَّافَّات",
    "ص",
    "ٱلزُّمَر",
    "غَافِر",
    "فُصِّلَت",
    "ٱلشُّورىٰ",
    "ٱلْزُّخْرُف",
    "ٱلدُّخَان",
    "ٱلْجَاثِيَة",
    "ٱلْأَحْقَاف",
    "مُحَمَّد",
    "ٱلْفَتْح",
    "ٱلْحُجُرَات",
    "ق",
    "ٱلذَّارِيَات",
    "ٱلطُّور",
    "ٱلنَّجْم",
    "ٱلْقَمَر",
    "ٱلرَّحْمَٰن",
    "ٱلْوَاقِعَة",
    "ٱلْحَدِيد",
    "ٱلْمُجَادِلَة",
    "ٱلْحَشْر",
    "ٱلْمُمْتَحَنَة",
    "ٱلصَّفّ",
    "ٱلْجُمُعَة",
    "ٱلْمُنَافِقُون",
    "ٱلتَّغَابُن",
    "ٱلطَّلَاق",
    "ٱلتَّحْرِيم",
    "ٱلْمُلْك",
    "ٱلْقَلَم",
    "ٱلْحَاقَّة",
    "ٱلْمَعَارِج",
    "نُوح",
    "ٱلْجِنّ",
    "ٱلْمُزَّمِّل",
    "ٱلْمُدَّثِّر",
    "ٱلْقِيَامَة",
    "ٱلْإِنْسَان",
    "ٱلْمُرْسَلَات",
    "ٱلنَّبَأ",
    "ٱلنَّازِعَات",
    "عَبَسَ",
    "ٱلتَّكْوِير",
    "ٱلْإِنْفِطَار",
    "ٱلْمُطَفِّفِين",
    "ٱلْإِنْشِقَاق",
    "ٱلْبُرُوج",
    "ٱلطَّارِق",
    "ٱلْأَعْلَىٰ",
    "ٱلْغَاشِيَة",
    "ٱلْفَجْر",
    "ٱلْبَلَد",
    "ٱلشَّمْس",
    "ٱللَّيْل",
    "ٱلضُّحَىٰ",
    "ٱلشَّرْح",
    "ٱلتِّين",
    "ٱلْعَلَق",
    "ٱلْقَدْر",
    "ٱلْبَيِّنَة",
    "ٱلزَّلْزَلَة",
    "ٱلْعَادِيَات",
    "ٱلْقَارِعَة",
    "ٱلتَّكَاثُر",
    "ٱلْعَصْر",
    "ٱلْهُمَزَة",
    "ٱلْفِيل",
    "قُرَيْش",
    "ٱلْمَاعُون",
    "ٱلْكَوْثَر",
    "ٱلْكَافِرُون",
    "ٱلنَّصْر",
    "ٱلْمَسَد",
    "ٱلْإِخْلَاص",
    "ٱلْفَلَق",
    "ٱلنَّاس"
  ];

  List<String> suraNamesEnglish = [
    "Al-Fatihah",
    "Al-Baqarah",
    "Ali 'Imran",
    "An-Nisa",
    "Al-Ma'idah",
    "Al-An'am",
    "Al-A'raf",
    "Al-Anfal",
    "At-Tawbah",
    "Yunus",
    "Hud",
    "Yusuf",
    "Ar-Ra'd",
    "Ibrahim",
    "Al-Hijr",
    "An-Nahl",
    "Al-Isra",
    "Al-Kahf",
    "Maryam",
    "Ta-Ha",
    "Al-Anbiya",
    "Al-Hajj",
    "Al-Mu'minun",
    "An-Nur",
    "Al-Furqan",
    "Ash-Shu'ara",
    "An-Naml",
    "Al-Qasas",
    "Al-Ankabut",
    "Ar-Rum",
    "Luqmaan",
    "As-Sajdah",
    "Al-Ahzaab",
    "Saba",
    "Faatir",
    "Ya-Sin",
    "As-Saaffaat",
    "Saad",
    "Az-Zumar",
    "Ghafir",
    "Fussilat",
    "Ash-Shura",
    "Az-Zukhruf",
    "Ad-Dukhaan",
    "Al-Jaathiyah",
    "Al-Ahqaaf",
    "Muhammad",
    "Al-Fath",
    "Al-Hujuraat",
    "Qaaf",
    "Adh-Dhaariyaat",
    "At-Toor",
    "An-Najm",
    "Al-Qamar",
    "Ar-Rahman",
    "Al-Waqi'a",
    "Al-Hadeed",
    "Al-Mujadila",
    "Al-Hashr",
    "Al-Mumtahanah",
    "As-Saff",
    "Al-Jumu'ah",
    "Al-Munafiqoon",
    "At-Taghabun",
    "At-Talaq",
    "At-Tahreem",
    "Al-Mulk",
    "Al-Qalam",
    "Al-Haaqqa",
    "Al-Ma'aarij",
    "Nuh",
    "Al-Jinn",
    "Al-Muzzammil",
    "Al-Muddaththir",
    "Al-Qiyamah",
    "Al-Insaan",
    "Al-Mursalaat",
    "An-Naba'",
    "An-Naazi'aat",
    "Abasa",
    "At-Takweer",
    "Al-Infitar",
    "Al-Mutaffifeen",
    "Al-Inshiqaaq",
    "Al-Burooj",
    "At-Taariq",
    "Al-A'la",
    "Al-Ghaashiyah",
    "Al-Fajr",
    "Al-Balad",
    "Ash-Shams",
    "Al-Layl",
    "Ad-Dhuha",
    "Ash-Sharh",
    "At-Tin",
    "Al-Alaq",
    "Al-Qadr",
    "Al-Bayyinahh",
    "Az-Zalzalah",
    "Al-'Adiyat",
    "Al-Qaari'ah",
    "At-Takathur",
    "Al-'Asr",
    "Al-Humazah",
    "Al-Fil",
    "Quraysh",
    "Al-Maa'oon",
    "Al-Kawthar",
    "Al-Kaafiroon",
    "An-Nasr",
    "Al-Masad",
    "Al-Ikhlaas",
    "Al-Falaq",
    "An-Naas",
    ];

  List<int> suraAyatNumber = [7, 286, 200,
    176,
    120,
    165,
    206,
    75,
    129,
    109,
    123,
    111,
    43,
    52,
    99,
    128,
    111,
    110,
    98,
    135,
    112,
    78,
    118,
    64,
    77,
    227,
    93,
    88,
    69,
    60,
    34,
    30,
    73,
    54,
    45,
    83,
    182,
    88,
    75,
    85,
    54,
    53,
    89,
    59,
    37,
    35,
    38,
    29,
    18,
    45,
    60,
    49,
    62,
    55,
    78,
    96,
    29,
    22,
    24,
    13,
    14,
    11,
    11,
    18,
    12,
    12,
    30,
    52,
    52,
    44,
    28,
    28,
    20,
    56,
    40,
    31,
    50,
    40,
    46,
    42,
    29,
    19,
    36,
    25,
    22,
    17,
    19,
    26,
    30,
    20,
    15,
    21,
    11,
    8,
    5,
    19,
    5,
    8,
    8,
    11,
    11,
    8,
    3,
    9,
    5,
    4,
    6,
    3,
    6,
    3,
    5,
    4,
    5,
    6
  ];

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.center,
      children: [
        const Expanded(
          flex: 3,
          child: Image(image: AssetImage('assets/images/quran_logo.png')),
        ),
        Divider(
          color: darkMode == true ? const Color(0xffFACC1D) : MyThemeData
              .primaryColor,
          thickness: 3.0,
        ),

        Padding(
          padding: const EdgeInsets.symmetric(vertical: 4.0),
          child: Row(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Text(
                "اسم السورة",
                style: TextStyle(
                    fontSize: 25, fontWeight: FontWeight.w500,
                    color: darkMode == true ? Colors.white : Colors.black
                ),
              ),
            ],
          ),
        ),
        Divider(
          color: darkMode == true ? const Color(0xffFACC1D) : MyThemeData
              .primaryColor,
          thickness: 3.0,
        ),
        Expanded(
            flex: 7,
            child: Theme(
              data: Theme.of(context).copyWith(
                  scrollbarTheme: ScrollbarThemeData(
                      thumbColor: MaterialStateProperty.all(
                          MyThemeData.primaryColor),
                      crossAxisMargin: 5
                  )
              ),
              child: Scrollbar(
                thickness: 8,
                interactive: false,
                showTrackOnHover: true,
                radius: const Radius.circular(15),
                child: ListView.separated(
                    physics: const BouncingScrollPhysics(),
                    itemBuilder: (context, index) =>
                        SuraName(
                          suraName: suraNamesList[index],
                          index: index,
                          ayatNumbers: suraAyatNumber[index],
                          suraNameInEnglish: suraNamesEnglish[index],
                        ),
                    separatorBuilder: (context, index) {
                      return Divider(
                        indent: 15,
                        endIndent: 15,
                        color: darkMode == true
                            ? const Color(0xffFACC1D)
                            : MyThemeData.primaryColor,
                        thickness: 1,
                      );
                    },
                    itemCount: suraNamesList.length),
              ),
            ))

      ],
    );
  }

  Widget suraBuilder(index) {
    return Container(
        color: Colors.black,
        child: Column(
          children: [
            SuraName(suraName: suraNamesList[index],
                index: index,
                ayatNumbers: suraAyatNumber[index],
                suraNameInEnglish: suraNamesEnglish[index],
            ),
            Text("anything")
          ],
        )
    );
  }
}
